---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-sa
  namespace: tanzu-packages