apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    tmc.cloud.vmware.com/managed-helm-release-name: helm-contour
  name: helm-contour
  namespace: tanzu-helm-resources
spec:
  chart:
    spec:
      chart: contour
      valuesFiles: 
      - values.yaml
      version: '12.4.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
  install:
    createNamespace: true
  targetNamespace: contour
  interval: 10m0s