apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '15.1.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
      interval: 1m
  values:
    replicaCount: 2