apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- pkgi.yaml
secretGenerator:
- name: contour-packages-values
  namespace: tanzu-packages
  files:
  - values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: contour-packages