apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tanzu-helm-resources-cert-manager
  namespace: tanzu-helm
spec:
  chart:
    spec:
      chart: cert-manager
      valuesFile: values.yaml
      version: '0.11.9'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
  interval: 10m0s