apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      valuesFiles: 
      - values.yaml
      version: '0.11.9'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
  interval: 10m0s