apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tanzu-helm-resources-cert-manager
  namespace: tanzu-helm
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 0.11.9
  install:
    createNamespace: true
  interval: 10m0s
  serviceAccountName: cert-manager-helm-sa
  targetNamespace: cert-manager
  valuesFrom:
  - kind: Secret
    name: cert-manager-helm-values
    valuesKey: values.yaml