apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    tmc.cloud.vmware.com/managed-helm-release-name: helm-cert-manager
  name: helm-cert-manager
  namespace: tanzu-helm-resources
spec:
  chart:
    spec:
      chart: cert-manager
      valuesFiles: 
      - ./others/helm/cert-manager/values.yaml
      version: '0.11.9'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
  interval: 10m0s
  valuesFrom:
  - kind: Secret
    name: cert-manager-values
    valuesKey: values.yaml