apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- helmrelease.yaml
secretGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=cert-manager-values.yaml