apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- helmrelease.yaml
secretGenerator:
- name: values
  namespace: tanzu-helm-resources
  files:
  - values.yaml
  type: Opaque