apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- helmrelease.yaml
secretGenerator:
- name: cert-manager-helm-values
  namespace: tanzu-helm
  files:
  - values.yaml
  type: Opaque
  options:
    annotations:
      tmc.cloud.vmware.com/managed-helm-release-name: tanzu-helm-resources-cert-manager