apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: tanzu-helm-resources
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: cert-manager-helm-values
  namespace: tanzu-helm-resources
  files:
  - values.yaml
  type: Opaque