---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-ns
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./namespaces/tanzu-packages
  prune: true
  sourceRef:
    kind: GitRepository
    name: tmc-demo-kustomization 
    namespace: tanzu-continuousdelivery-resources