---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-pkgi
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-ns
    - name: cert-manager-sa
  interval: 1m0s
  path: ./tanzu/pkgi/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-kustomization
    namespace: tanzu-continuousdelivery-resources
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour-pkgi
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-ns
    - name: contour-sa
    - name: cert-manager-pkgi
  interval: 1m0s
  path: ./tanzu/pkgi/contour
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-kustomization
    namespace: tanzu-continuousdelivery-resources