---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-helm
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: cert-manager-ns
  interval: 1m0s
  path: ./others/helm/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-kustomization
    namespace: tanzu-continuousdelivery-resources