---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-ns
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./others/namespaces/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-kustomization
    namespace: tanzu-continuousdelivery-resources